### PR TITLE
Actual typo - incorrect year

### PR DESCRIPTION
**Pull request by PepperSwan**

### CODE REVIEW

**Comment by drvinceknight** [comment]
Was this the one @alcarney found and wanted to pass to @Laura-Mae?

**Comment by Laura-Mae** [comment]
yeah oliver sort of showed me how to change it in the lecture but I couldn't work out how to edit the title for some reason

**Comment by drvinceknight** [comment]
Ok, want me to leave this for you to do or should I just 'merge' (accept @PepperSwan's changes). There's one very specific typo that I've got that I could use to show you how if that's helpful?

**Comment by Laura-Mae** [comment]
Sure you can merge it, but it would be cool to see how to fix the one you've got?

**Comment by drvinceknight** [comment]
> Sure you can merge it, but it would be cool to see how to fix the one you've got?

Cool. Just let me know when.

**Comment by Laura-Mae** [comment]
I might wander over to maths sometime tomorrow afternoon?

**Comment by drvinceknight** [comment]
Great: I'll be around after 1500 (meetings before then).

**Comment by Laura-Mae** [comment]
My dad just called me and I think I'm going home today instead of tomorrow but I haven't finished packing yet! I'm not sure if I'll have time to come to maths, sorry! :(

**Comment by drvinceknight** [comment]
No problem. It can wait till 2016: just let me know :)

Have a great christmas and good luck with the exams 🎄👍

**Comment by Laura-Mae** [comment]
Thanks :)
Merry christmas!

**Pull request merged**
